### ISSUE TITLE
can you give some example?

### ISSUE THREAD

**Issue by marlti7** [erin-noe-payne/react-native-custom-input-view#1]

**Comment by erin-noe-payne** [comment]
This just doesn't work, I'm sorry. 

I was trying hard to come up with a way to build cross-platform custom keyboards tying into native text inputs, but in the end it didn't work out. Ultimately I found it was much easier to just build my own view that looks like a keyboard and interacts with text inputs at the react layer.

If you only need ios support, you can follow the approach shown here: https://github.com/reactnativecn/react-native-custom-keyboard

I need to unpublish this repo - sorry for the confusion =(
